"""add_performance_indexes

Revision ID: 00713955c54f
Revises: 9c0d1e2f3a4b
Create Date: 2026-09-08 17:01:16.425931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00713955c54f'
down_revision: Union[str, Sequence[str], None] = '9c0d1e2f3a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contributions_trip_created', 'contributions', ['trip_id', 'created_at'], unique=False)
    op.create_index('ix_expense_splits_expense_id', 'expense_splits', ['expense_id'], unique=False)
    op.create_index('ix_expense_splits_member_id', 'expense_splits', ['member_id'], unique=False)
    op.create_index('ix_expenses_trip_created', 'expenses', ['trip_id', 'created_at'], unique=False)
    op.create_index('ix_wallet_tx_wallet_created', 'wallet_transactions', ['wallet_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallet_tx_wallet_created', table_name='wallet_transactions')
    op.drop_index('ix_expenses_trip_created', table_name='expenses')
    op.drop_index('ix_expense_splits_member_id', table_name='expense_splits')
    op.drop_index('ix_expense_splits_expense_id', table_name='expense_splits')
    op.drop_index('ix_contributions_trip_created', table_name='contributions')
    # ### end Alembic commands ###
