"""add expense idempotency key

Revision ID: 1aafc139f02e
Revises: fc43e1d2edd2
Create Date: 2026-09-05 20:04:15.875118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aafc139f02e'
down_revision: Union[str, Sequence[str], None] = 'fc43e1d2edd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add the column temporarily as nullable so existing
    # expense records can be populated.
    op.add_column(
        "expenses",
        sa.Column(
            "idempotency_key",
            sa.String(length=100),
            nullable=True,
        ),
    )

    # Generate a unique key for existing expense records.
    op.execute(
        """
        UPDATE expenses
        SET idempotency_key = 'legacy-' || id::text
        WHERE idempotency_key IS NULL
        """
    )

    # Make the column mandatory for all future records.
    op.alter_column(
        "expenses",
        "idempotency_key",
        existing_type=sa.String(length=100),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'idempotency_key')
    # ### end Alembic commands ###
