"""create_payment_webhook_events_table

Revision ID: 67621b1c69c6
Revises: 6e1033033755
Create Date: 2026-09-16 19:28:31.034218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67621b1c69c6'
down_revision: Union[str, Sequence[str], None] = '6e1033033755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_webhook_events_event_id'), 'payment_webhook_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_webhook_events_event_id'), table_name='payment_webhook_events')
    op.drop_table('payment_webhook_events')
    # ### end Alembic commands ###
