"""add expense idempotency constraint

Revision ID: 69a2886ae660
Revises: fd44f4ba5558
Create Date: 2026-09-05 20:35:01.951462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a2886ae660'
down_revision: Union[str, Sequence[str], None] = 'fd44f4ba5558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_expense_idempotency', 'expenses', ['trip_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_expense_idempotency', 'expenses', type_='unique')
    # ### end Alembic commands ###
