"""link payments to contributions

Revision ID: 6e1033033755
Revises: 093d67961062
Create Date: 2026-09-15 06:24:25.715933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1033033755'
down_revision: Union[str, Sequence[str], None] = '093d67961062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('contribution_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payments_contribution_id'), 'payments', ['contribution_id'], unique=True)
    op.create_foreign_key(None, 'payments', 'contributions', ['contribution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_contribution_id'), table_name='payments')
    op.drop_column('payments', 'contribution_id')
    # ### end Alembic commands ###
