"""add_contribution_verification_fields_and_trip_admin_upi

Revision ID: db49298af483
Revises: e684b5a8df81
Create Date: 2026-09-17 15:29:11.984545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db49298af483'
down_revision: Union[str, Sequence[str], None] = 'e684b5a8df81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('payment_reference', sa.String(length=100), nullable=True))
    op.add_column('contributions', sa.Column('confirmed_by', sa.Uuid(), nullable=True))
    op.add_column('contributions', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('contributions', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'contributions', 'users', ['confirmed_by'], ['id'])
    op.add_column('trips', sa.Column('admin_upi_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'admin_upi_id')
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.drop_column('contributions', 'rejection_reason')
    op.drop_column('contributions', 'confirmed_at')
    op.drop_column('contributions', 'confirmed_by')
    op.drop_column('contributions', 'payment_reference')
    # ### end Alembic commands ###
