"""create payment_refunds table

Revision ID: e684b5a8df81
Revises: 67621b1c69c6
Create Date: 2026-09-16 19:55:53.204266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e684b5a8df81'
down_revision: Union[str, Sequence[str], None] = '67621b1c69c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_refunds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_refund_id', sa.String(length=100), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_refunds_payment_id'), 'payment_refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_refunds_provider_refund_id'), 'payment_refunds', ['provider_refund_id'], unique=True)
    op.create_index(op.f('ix_payment_refunds_trip_id'), 'payment_refunds', ['trip_id'], unique=False)
    op.create_index(op.f('ix_payment_refunds_user_id'), 'payment_refunds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_refunds_user_id'), table_name='payment_refunds')
    op.drop_index(op.f('ix_payment_refunds_trip_id'), table_name='payment_refunds')
    op.drop_index(op.f('ix_payment_refunds_provider_refund_id'), table_name='payment_refunds')
    op.drop_index(op.f('ix_payment_refunds_payment_id'), table_name='payment_refunds')
    op.drop_table('payment_refunds')
    # ### end Alembic commands ###
