"""add contribution idempotency

Revision ID: fc43e1d2edd2
Revises: 52ae6792c712
Create Date: 2026-09-05 16:59:20.031744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc43e1d2edd2'
down_revision: Union[str, Sequence[str], None] = '52ae6792c712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('idempotency_key', sa.String(length=100), nullable=False))
    op.create_unique_constraint('uq_contribution_idempotency', 'contributions', ['trip_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_contribution_idempotency', 'contributions', type_='unique')
    op.drop_column('contributions', 'idempotency_key')
    # ### end Alembic commands ###
