"""add request hashes

Revision ID: fd44f4ba5558
Revises: 1aafc139f02e
Create Date: 2026-09-05 20:12:25.133432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd44f4ba5558'
down_revision: Union[str, Sequence[str], None] = '1aafc139f02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add columns temporarily as nullable.
    op.add_column(
        "contributions",
        sa.Column(
            "request_hash",
            sa.String(length=64),
            nullable=True,
        ),
    )

    op.add_column(
        "expenses",
        sa.Column(
            "request_hash",
            sa.String(length=64),
            nullable=True,
        ),
    )

    # Give existing records deterministic legacy hashes.
    op.execute(
        """
        UPDATE contributions
        SET request_hash = md5('legacy-contribution-' || id::text)
        WHERE request_hash IS NULL
        """
    )

    op.execute(
        """
        UPDATE expenses
        SET request_hash = md5('legacy-expense-' || id::text)
        WHERE request_hash IS NULL
        """
    )

    # Make the fields mandatory for all new records.
    op.alter_column(
        "contributions",
        "request_hash",
        existing_type=sa.String(length=64),
        nullable=False,
    )

    op.alter_column(
        "expenses",
        "request_hash",
        existing_type=sa.String(length=64),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'request_hash')
    op.drop_column('contributions', 'request_hash')
    # ### end Alembic commands ###
